libtextworker: libtextworker.interface.wx.about.AboutDialog Class Reference
libtextworker.interface.wx.about.AboutDialog Class Reference
About dialog built with wxPython.
Public Member Functions
def SetArtists (self, artists)
def SetCopyright (self, str text)
def SetDescription (self, str des)
def SetDevelopers (self, developers)
def SetDocWriters (self, writers)
def SetIcon (self, wx.Icon icon)
def SetLicense (self, str license)
Set the long, multiline string containing the text of the program license.
def SetName (self, str name)
def SetTranslators (self, translators)
def SetVersion (self, str|float version, str longversion="")
def SetWebSite (self, str address)
def ShowBox (self, event=None)
Shows a About dialog with infomations collected.
Static Public Attributes
infos = wx.adv.AboutDialogInfo()
None
Detailed Description
About dialog built with wxPython.
All self-set infomations are stored in the infos attribute. Just run ShowBox(). You can set the parent of the dialog if needed, use the Parent variable.
Member Function Documentation
SetArtists()
def libtextworker.interface.wx.about.AboutDialog.SetArtists (self, artists)
SetCopyright()
def libtextworker.interface.wx.about.AboutDialog.SetCopyright (self, str text)
SetDescription()
def libtextworker.interface.wx.about.AboutDialog.SetDescription (self, str des)
SetDevelopers()
def libtextworker.interface.wx.about.AboutDialog.SetDevelopers (self, developers)
SetDocWriters()
def libtextworker.interface.wx.about.AboutDialog.SetDocWriters (self, writers)
SetIcon()
def libtextworker.interface.wx.about.AboutDialog.SetIcon (self, wx.Icon icon)
SetLicense()
def libtextworker.interface.wx.about.AboutDialog.SetLicense (self, str license)
Set the long, multiline string containing the text of the program license.
Not all license types are available. Please see the attribute available_licenses (not in this class but in the same module).
SetName()
def libtextworker.interface.wx.about.AboutDialog.SetName (self, str name)
SetTranslators()
def libtextworker.interface.wx.about.AboutDialog.SetTranslators (self, translators)
SetVersion()
def libtextworker.interface.wx.about.AboutDialog.SetVersion (self, str | float version, str longversion = "")
SetWebSite()
def libtextworker.interface.wx.about.AboutDialog.SetWebSite (self, str address)
ShowBox()
def libtextworker.interface.wx.about.AboutDialog.ShowBox (self, event = None)
Shows a About dialog with infomations collected.
Parameters
event | None: wxPython event
Returns
wx.adv.AboutBox: About window
Member Data Documentation
infos
libtextworker.interface.wx.about.AboutDialog.infos = wx.adv.AboutDialogInfo() static
Referenced by libtextworker.interface.wx.about.AboutDialog.SetArtists(), libtextworker.interface.wx.about.AboutDialog.SetCopyright(), libtextworker.interface.wx.about.AboutDialog.SetDescription(), libtextworker.interface.wx.about.AboutDialog.SetDevelopers(), libtextworker.interface.wx.about.AboutDialog.SetDocWriters(), libtextworker.interface.wx.about.AboutDialog.SetIcon(), libtextworker.interface.wx.about.AboutDialog.SetLicense(), libtextworker.interface.wx.about.AboutDialog.SetName(), libtextworker.interface.wx.about.AboutDialog.SetTranslators(), libtextworker.interface.wx.about.AboutDialog.SetVersion(), libtextworker.interface.wx.about.AboutDialog.SetWebSite(), and libtextworker.interface.wx.about.AboutDialog.ShowBox().
None
libtextworker.interface.wx.about.AboutDialog.None static
The documentation for this class was generated from the following file:
libtextworker/interface/wx/about.py