libtextworker: libtextworker.general.Logger Class Reference
libtextworker.general.Logger Class Reference
Public Member Functions
UseGUIToolKit (self, available_toolkits toolkit)
critical (self, object msg, *object args, **kwds)
debug (self, object msg, *object args, **kwds)
error (self, object msg, *object args, **kwds)
exception (self, object msg, *object args, **kwds)
log (self, int level, object msg, *object args, **kwds)
warning (self, object msg, *object args, **kwds)
Public Attributes
UseToolKit
Member Function Documentation
critical()
libtextworker.general.Logger.critical (self, object msg, *object args, ** kwds)
References libtextworker.general.Logger.critical().
Referenced by libtextworker.general.Logger.critical().
debug()
libtextworker.general.Logger.debug (self, object msg, *object args, ** kwds)
References libtextworker.general.Logger.debug().
Referenced by libtextworker.general.Logger.debug().
error()
libtextworker.general.Logger.error (self, object msg, *object args, ** kwds)
References libtextworker.general.Logger.error().
Referenced by libtextworker.general.Logger.error().
exception()
libtextworker.general.Logger.exception (self, object msg, *object args, ** kwds)
References libtextworker.general.Logger.exception().
Referenced by libtextworker.general.Logger.exception().
log()
libtextworker.general.Logger.log (self, int level, object msg, *object args, ** kwds)
References libtextworker.general.Logger.log().
Referenced by libtextworker.general.Logger.log().
UseGUIToolKit()
libtextworker.general.Logger.UseGUIToolKit (self, available_toolkits toolkit)
warning()
libtextworker.general.Logger.warning (self, object msg, *object args, ** kwds)
References libtextworker.general.Logger.warning().
Referenced by libtextworker.general.Logger.warning().
Member Data Documentation
UseToolKit
libtextworker.general.Logger.UseToolKit
The documentation for this class was generated from the following file:
libtextworker/general.py