libtextworker: libtextworker.versioning Namespace Reference
libtextworker.versioning Namespace Reference
Functions
parse_version (str project)
Try to import a project then parse its version with the packaging.version module.
is_development_version (str version)
Parse and check if the specified version is a prerelease.
is_development_version_from_project (str project)
Like is_development_version(), but read the project's current version instead.
require (str project, str target_version)
Ensures the correct versions of a project are available.
require_exact (str project, str target_version)
Ensures the correct version of a project IS available.
require_lower (str project, str target_version)
Ensures the project version is LOWER than the requested one.
Variables
dict Requested = {}
Function Documentation
is_development_version()
libtextworker.versioning.is_development_version (str version)
Parse and check if the specified version is a prerelease.
See also
is_development_version_from_project
Referenced by libtextworker.versioning.is_development_version_from_project().
is_development_version_from_project()
libtextworker.versioning.is_development_version_from_project (str project)
Like is_development_version(), but read the project's current version instead.
See also
is_development_version
References libtextworker.versioning.is_development_version(), and libtextworker.versioning.parse_version().
parse_version()
libtextworker.versioning.parse_version (str project)
Try to import a project then parse its version with the packaging.version module.
Parsed projects are stored in Requested (list).
See also
is_development_version
is_development_from_project
require
require_exact
require_lower
Requested
Referenced by libtextworker.versioning.is_development_version_from_project(), libtextworker.versioning.require(), libtextworker.versioning.require_exact(), and libtextworker.versioning.require_lower().
require()
libtextworker.versioning.require (str project, str target_version)
Ensures the correct versions of a project are available.
Parameters
project (str): Target project name
target_version (str): Target project version
References libtextworker.versioning.parse_version().
require_exact()
libtextworker.versioning.require_exact (str project, str target_version)
Ensures the correct version of a project IS available.
Parameters
project (str): Target project name
target_version (str): Target project version
References libtextworker.versioning.parse_version().
require_lower()
libtextworker.versioning.require_lower (str project, str target_version)
Ensures the project version is LOWER than the requested one.
Parameters
project (str): Target project name
target_version (str): Target project version
References libtextworker.versioning.parse_version().
Variable Documentation
Requested
dict libtextworker.versioning.Requested = {}