libtextworker: libtextworker.interface.manager.ColorManager Class Reference
libtextworker.interface.manager.ColorManager Class Reference
A color manager for GUI widgets.
Public Member Functions
def __init__ (self, dict[str, typing.Any] default_configs, str or bool customfilepath=False)
Constructor of the class.
def reset (self, bool restore=False)
Reset the configuration file.
def backup (self, str file)
Backup a file to another file.
def GetFont (self)
Property of ColorManager to call the font definitions.
def GetFont (self, typing.Callable func)
def GetFont (self)
def GetColor (self)
Property of ColorManager to call the color definitions.
def GetColor (self, typing.Callable func)
def GetColor (self)
def setcolorfunc (self, str objname, typing.Callable func, dict params)
Set wxPython widgets background color function.
def setfontcfunc (self, str objname, typing.Callable func, dict params)
Set wxPython widgets background color function.
def configure (self, typing.Any widget)
Configure a widget with pre-defined settings.
Public Member Functions inherited from libtextworker.get_config.GetConfig
def __init__ (self, dict config, str file, **kwds)
Customized configuration parser.
def readf (self, str file, str|None encoding=None)
bool reset (self, bool restore=False)
def update (self)
dict backup (self, dict keys, bool direct_to_keys=False)
Backs up user data, specified by the keys parameter (dictionary).
str|bool getkey (self, str section, str option, bool needed=False, bool restore=False, bool noraiseexp=False, bool getbool=returnbool)
Try to get the value of an option under the spectified section.
None aliasyesno (self, yesvalue, novalue, bool enable=True)
Use a custom yes/no value, for example: There is an option under [section], and GetConfig will return True if the options is 'yes', False if the options is 'no'.
None alias (self, value, value2)
Static Public Attributes
dict setcolorfn = {}
dict setfontfn = {}
Static Public Attributes inherited from libtextworker.get_config.GetConfig
list yes_values = []
list no_values = []
bool returnbool = True
dict aliases = {}
bool detailedlogs = True
dict backups = {}
Protected Member Functions
def _get_font (self)
def _get_color (self)
Protected Attributes
_get_font
_get_color
Additional Inherited Members
Public Attributes inherited from libtextworker.get_config.GetConfig
cfg
returnbool
Static Protected Attributes inherited from libtextworker.get_config.GetConfig
list _yes_values = ["yes", "True"]
list _no_values = ["no", "False"]
Detailed Description
A color manager for GUI widgets.
ColorManager reads configs from a file (default is under THEMES_DIR)
Constructor & Destructor Documentation
__init__()
def libtextworker.interface.manager.ColorManager.__init__ (self, dict[str, typing.Any] default_configs, str or bool customfilepath = False)
Constructor of the class.
Parameters
default_configs (dict[str, Any]): Defaults to default_configs, this is dev-made configs
customfilepath (str|bool): Custom file path support. Set to False (default) or "" to disable it.
Reimplemented from libtextworker.get_config.GetConfig.
Referenced by libtextworker.interface.manager.ColorManager.__init__().
Member Function Documentation
_get_color()
def libtextworker.interface.manager.ColorManager._get_color (self) protected
Referenced by libtextworker.interface.manager.ColorManager.configure(), and libtextworker.interface.manager.ColorManager.GetColor().
_get_font()
def libtextworker.interface.manager.ColorManager._get_font (self) protected
Referenced by libtextworker.interface.manager.ColorManager.configure(), and libtextworker.interface.manager.ColorManager.GetFont().
backup()
def libtextworker.interface.manager.ColorManager.backup (self, str file)
Backup a file to another file.
Parameters
file : str : Target backup file
Reimplemented from libtextworker.get_config.GetConfig.
configure()
def libtextworker.interface.manager.ColorManager.configure (self, typing.Any widget)
Configure a widget with pre-defined settings.
This function also ables to rerun itself under a threading thread.
Parameters
widget : Widget to configure
See also
setcolorfunc
setfontcfunc
Referenced by libtextworker.interface.manager.ColorManager.configure().
GetColor() [1/3]
def libtextworker.interface.manager.ColorManager.GetColor (self)
Property of ColorManager to call the color definitions.
When called, it returns the following: background color, foreground color (in hex-rgb format)
GetColor() [2/3]
def libtextworker.interface.manager.ColorManager.GetColor (self)
GetColor() [3/3]
def libtextworker.interface.manager.ColorManager.GetColor (self, typing.Callable func)
GetFont() [1/3]
def libtextworker.interface.manager.ColorManager.GetFont (self)
Property of ColorManager to call the font definitions.
When called, this returns the following: (font) size (int|str), style, weight, family
GetFont() [2/3]
def libtextworker.interface.manager.ColorManager.GetFont (self)
GetFont() [3/3]
def libtextworker.interface.manager.ColorManager.GetFont (self, typing.Callable func)
reset()
def libtextworker.interface.manager.ColorManager.reset (self, bool restore = False)
Reset the configuration file.
This is blocked as it can make conflicts with other GUI widgets - unless you shutdown the app immediately..
Reimplemented from libtextworker.get_config.GetConfig.
setcolorfunc()
def libtextworker.interface.manager.ColorManager.setcolorfunc (self, str objname, typing.Callable func, dict params)
Set wxPython widgets background color function.
Parameters
objname (str): Object name (for easier access)
func (callable): Function to set the background color (no arg)
params (dict): Parameters to pass to func
setfontcfunc()
def libtextworker.interface.manager.ColorManager.setfontcfunc (self, str objname, typing.Callable func, dict params)
Set wxPython widgets background color function.
Parameters
objname (str): Object name (for easier access)
func (callable): Function to set the background color (no arg)
params (dict): Parameters to pass to func
Member Data Documentation
_get_color
libtextworker.interface.manager.ColorManager._get_color protected
Referenced by libtextworker.interface.manager.ColorManager.configure(), and libtextworker.interface.manager.ColorManager.GetColor().
_get_font
libtextworker.interface.manager.ColorManager._get_font protected
Referenced by libtextworker.interface.wx.ColorManager._get_font(), libtextworker.interface.manager.ColorManager.configure(), and libtextworker.interface.manager.ColorManager.GetFont().
setcolorfn
dict libtextworker.interface.manager.ColorManager.setcolorfn = {} static
Referenced by libtextworker.interface.manager.ColorManager.configure(), and libtextworker.interface.manager.ColorManager.setcolorfunc().
setfontfn
dict libtextworker.interface.manager.ColorManager.setfontfn = {} static
Referenced by libtextworker.interface.manager.ColorManager.configure(), and libtextworker.interface.manager.ColorManager.setfontcfunc().
The documentation for this class was generated from the following file:
C:/Users/Regmina/Desktop/Projects/libtextworker/libtextworker/interface/manager.py