libtextworker: libtextworker.general Namespace Reference
libtextworker.general Namespace Reference
Classes
class libTewException
Common exception class for libtextworker.
Functions
str CraftItems (str or pathlib.Path path1, str or pathlib.Path path2)
Craft 2 paths together.
def CreateDirectory (str directory, list[str] childs=[])
Create a directory with optional sub-folders.
def WalkCreation (str directory)
Create directory layer-to-layer.
def GetCurrentDir (str file, bool aspathobj=False)
Get the current directory path.
def ResetEveryConfig ()
Reset every configurations under ~/.config/textworker to default.
Variables
string separator = "\\"
bool
LOG_PATH = os.path.expanduser("~/libtew.log")
logger = logging.getLogger("textworker")
console_hdlr = logging.StreamHandler()
file_hdlr = logging.FileHandler(LOG_PATH)
formatter = logging.Formatter("%(asctime)s %(name)s->%(levelname)s : %(message)s")
Function Documentation
CraftItems()
str libtextworker.general.CraftItems (str or pathlib.Path path1, str or pathlib.Path path2)
Craft 2 paths together.
Parameters
path1 (str|pathlib.Path)
path2 (str|pathlib.Path)
Returns
str: Result
Referenced by libtextworker.general.CreateDirectory(), and libtextworker.interface.wx.about.AboutDialog.SetLicense().
CreateDirectory()
def libtextworker.general.CreateDirectory (str directory, list[str] childs = [])
Create a directory with optional sub-folders.
Parameters
directory (str): Directory to create
childs (list of str): Sub-dirs under @directory @raise Exception: Directory creation failed
Referenced by libtextworker.general.ResetEveryConfig().
GetCurrentDir()
def libtextworker.general.GetCurrentDir (str file, bool aspathobj = False)
Get the current directory path.
Parameters
file (str): File path
aspathobj (bool): Return pathlib.Path type instead of a string.
Returns
pathlib.Path | str
Referenced by libtextworker.interface.wx.about.AboutDialog.SetLicense().
ResetEveryConfig()
def libtextworker.general.ResetEveryConfig ()
Reset every configurations under ~/.config/textworker to default.
Will close the app after completed.
WalkCreation()
def libtextworker.general.WalkCreation (str directory)
Create directory layer-to-layer.
How to understand this? Try this path: path1/path2/path3. WalkCreation will create path1 first, then path2 and path3. Skip existing dirs, yes of course.
Parameters
directory (str): Directory to create @raise Exception: Directory creation failed
Referenced by libtextworker.get_config.GetConfig.readf().
Variable Documentation
bool
libtextworker.general.bool
console_hdlr
libtextworker.general.console_hdlr = logging.StreamHandler()
file_hdlr
libtextworker.general.file_hdlr = logging.FileHandler(LOG_PATH)
formatter
libtextworker.general.formatter = logging.Formatter("%(asctime)s %(name)s->%(levelname)s : %(message)s")
LOG_PATH
libtextworker.general.LOG_PATH = os.path.expanduser("~/libtew.log")
logger
libtextworker.general.logger = logging.getLogger("textworker")
separator
string libtextworker.general.separator = "\\"