libtextworker: builder Namespace Reference
builder Namespace Reference
Functions
def make_trans ()
def install ()
def build ()
def clean ()
Variables
parser
type
bool
help
nargs
opts = parser.parse_args()
Function Documentation
build()
def builder.build ()
References make_trans().
Referenced by clean().
clean()
def builder.clean ()
References build(), install(), and make_trans().
install()
def builder.install ()
References make_trans().
Referenced by clean().
make_trans()
def builder.make_trans ()
Referenced by build(), clean(), and install().
Variable Documentation
bool
builder.bool
help
builder.help
nargs
builder.nargs
opts
builder.opts = parser.parse_args()
parser
builder.parser
Initial value:
 =  argparse.ArgumentParser(
     description="Help setting up textworker easier",
     usage="'install' for install the project, 'build' to build, 'maketrans' to create translations (gettext required).\nThat's all.",
 )
type
builder.type