libtextworker: libtextworker.interface.tk.ColorManager Class Reference
libtextworker.interface.tk.ColorManager Class Reference
Public Member Functions
def setfontcfunc (self, str objname, typing.Callable func, dict params)
def setcolorfunc (self, str objname, typing.Callable func, dict params)
def configure (self, typing.Any widget, bool childs_too=recursive_configure)
def autocolor_run (self, typing.Any widget)
Public Attributes
is_shown
Static Public Attributes
bool
Member Function Documentation
autocolor_run()
def libtextworker.interface.tk.ColorManager.autocolor_run (self, typing.Any widget)
Referenced by libtextworker.interface.wx.ColorManager.configure(), and libtextworker.interface.tk.ColorManager.configure().
configure()
def libtextworker.interface.tk.ColorManager.configure (self, typing.Any widget, bool childs_too = recursive_configure)
Referenced by libtextworker.interface.manager.ColorManager.autocolor_run(), libtextworker.interface.tk.ColorManager.autocolor_run(), libtextworker.interface.wx.ColorManager.configure(), libtextworker.interface.tk.ColorManager.configure(), and libtextworker.interface.tk.textwidget.TextWidget.wrapmode().
setcolorfunc()
def libtextworker.interface.tk.ColorManager.setcolorfunc (self, str objname, typing.Callable func, dict params)
setfontcfunc()
def libtextworker.interface.tk.ColorManager.setfontcfunc (self, str objname, typing.Callable func, dict params)
Member Data Documentation
bool
libtextworker.interface.tk.ColorManager.bool static
is_shown
libtextworker.interface.tk.ColorManager.is_shown
The documentation for this class was generated from the following file:
libtextworker/interface/tk/__init__.py