name: Doxygen GitHub Pages Build Action

on:
#  push:
#   branches:
#     - main
#     - docs
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update APT repos and install doxygen
        run: |
          sudo apt update
          sudo apt install doxygen graphviz -y

      - name: Build the page
        run: |
          doxygen Doxyfile
        working-directory: docs
      
      - name: Publish
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: docs
          folder: docs/html
